added geocodes for each facility
Code-for-Funabashi/kosodate-map pull request #8
Opened 2021-03-13 13:46 UTC by Jumpo-523

geocode directoryにcsv形式でデータを追加しています。
[子育てマップ](https://www.city.funabashi.lg.jp/funakkonavi/map/0/index.html)の施設カテゴリごとにcsvデータをスクレープし、経度緯度情報を取得しました。

経度緯度情報がどれくらい正しいものかは、何件かピックアップしてテストする必要がありますね。

2021-03-15 04:12 UTC, aca-ta requested changes

2021-03-15 04:12 UTC, aca-ta commented on geodata/scraping_n_geocoding.ipynb
> +{
[IMO]
データ取得用のコードは別リポジトリ管理が良いと思います。
最近はリポジトリ単位でCI/CD管理するのが主流なので、リポジトリも同時にデプロイする単位で管理した方が良いと思います。

2021-03-15 04:12 UTC, aca-ta commented on geodata/scraping_n_geocoding.ipynb
> +{
[IMO]
データ取得スクリプトをipythonの形式で管理するのは、保守性や再利用性が低いので、
PythonのコードとしてPushしてほしいです！

2021-03-15 04:12 UTC, aca-ta commented
@Jumpo-523 
すみません、体調崩してレス遅れましたがコメントご確認お願いします！

2021-03-18 11:21 UTC, Jumpo-523 commented on geodata/一時保育.csv
> +若松幼稚園,〒273-0013船橋市若松2-3-3,047-431-7751,"{'northeast': {'lat': 35.6799572802915, 'lng': 139.9978598802915}, 'southwest': {'lat': 35.6772593197085, 'lng': 139.9951619197085}}"
下記のデータ構造でgeocodingされたデータが帰ってきます。
```
{'address_components': [{'long_name': '12',
    'short_name': '12',
    'types': ['premise']},
   {'long_name': '1',
    'short_name': '1',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '6-chōme',
    'short_name': '6-chōme',
    'types': ['political', 'sublocality', 'sublocality_level_3']},
   {'long_name': 'Maebaranishi',
    'short_name': 'Maebaranishi',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': 'Funabashi',
    'short_name': 'Funabashi',
    'types': ['locality', 'political']},
   {'long_name': 'Chiba',
    'short_name': 'Chiba',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'Japan',
    'short_name': 'JP',
    'types': ['country', 'political']},
   {'long_name': '274-0825',
    'short_name': '274-0825',
    'types': ['postal_code']}],
  'formatted_address': '6-chōme-1-12 Maebaranishi, Funabashi, Chiba 274-0825, Japan',
  'geometry': {'location': {'lat': 35.7027062, 'lng': 140.0254386},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 35.7040551802915,
     'lng': 140.0267875802915},
    'southwest': {'lat': 35.70135721970851, 'lng': 140.0240896197085}}},
  'place_id': 'ChIJzyO33BuAImARE7aauSNj9Bg',
  'plus_code': {'compound_code': 'P23G+35 Funabashi, 千葉県 Japan',
   'global_code': '8R72P23G+35'},
  'types': ['street_address']}
```

調べて気がつきましたが、
`'geometry': {'location': {'lat': 35.7027062, 'lng': 140.0254386},`という情報がPointのlocationデータとして利用すべき情報っぽいですね。

2021-03-18 11:27 UTC, Jumpo-523 commented on geodata/scraping_n_geocoding.ipynb
> +{
ありがとうございます！なるほど、確かにCICDを踏まえるとそちらの方がいいのか...
では、データだけこちらのレポジトリに残してコードは別に写します！

2021-03-18 11:38 UTC, Jumpo-523 commented on geodata/scraping_n_geocoding.ipynb
> +{
承知しました！

2021-03-18 11:49 UTC, Jumpo-523 commented
あと、geocodingの精度情報は、location_typeパラメタを見ればいいらしいです。
https://groups.google.com/g/google-maps-api-japan/c/vyrUei-QPRE?pli=1

2021-03-18 11:51 UTC, Jumpo-523 commented on geodata/一時保育.csv
> +若松幼稚園,〒273-0013船橋市若松2-3-3,047-431-7751,"{'northeast': {'lat': 35.6799572802915, 'lng': 139.9978598802915}, 'southwest': {'lat': 35.6772593197085, 'lng': 139.9951619197085}}"
ちょっとわからなかったです。。すみません。
ただ、The Maps JavaScript APIでは`Google uses the World Geodetic System WGS84 standard.`らしいです。（https://developers.google.com/maps/documentation/javascript/coordinates）

2021-03-21 07:05 UTC, Jumpo-523 commented
以下の2点に関して修正しました。

- スクレープ・データgeocode処理に利用したコードを別管理とする
    -  https://github.com/Code-for-Funabashi/Scrape-OpenData に格納しました。
- point dataを取得するように修正
    - https://github.com/Code-for-Funabashi/kosodate-map/pull/8#discussion_r596764749

2021-03-21 10:23 UTC, aca-ta commented on geodata/一時保育.csv
> +若松幼稚園,〒273-0013船橋市若松2-3-3,047-431-7751,"{'northeast': {'lat': 35.6799572802915, 'lng': 139.9978598802915}, 'southwest': {'lat': 35.6772593197085, 'lng': 139.9951619197085}}"
WGS84(世界測地系)ですね、ありがとうございます！

2021-03-21 10:28 UTC, aca-ta commented on geodata/scraping_n_geocoding.ipynb
> +{
気持ち的には、データは別の場所において、そちらを参照するようにしたいんですけどねー、、
データ拡充するとフロント側でDLしないといけないデータ量や描画に対するCPU負荷で激重になると思うので、
個人的にはフロントのコードと一緒にデータを配布する方法自体、将来的には変えたいなーと思ってます。

2021-03-21 10:34 UTC, aca-ta commented
ありがとうございます！
https://github.com/Code-for-Funabashi/Scrape-OpenData
こちらもPRあげていただけると 🙏

2021-03-21 10:36 UTC, aca-ta commented on geodata/一時保育.csv
> +若松幼稚園,〒273-0013船橋市若松2-3-3,047-431-7751,"{'lat': 35.6786083, 'lng': 139.9965109}"
[IMO]
lat, lngをcsvのカラムとして扱った方が、実装的にもファイルサイズ的にも小さくて良いと思ったんですがいかがでしょう？

```
施設名,住所,電話番号(代表),lat,lng
若松幼稚園,〒273-0013船橋市若松2-3-3,047-431-7751,35.6786083,139.9965109
```

2021-04-06 23:53 UTC, Jumpo-523 commented on geodata/一時保育.csv
> +若松幼稚園,〒273-0013船橋市若松2-3-3,047-431-7751,"{'lat': 35.6786083, 'lng': 139.9965109}"
すいません、見落としておりました！

>実装的にもファイルサイズ的にも小さくて良い
言われてみればサイズ変わってきますね。修正しますー！

2021-04-07 10:54 UTC, Jumpo-523 reviewed
- lat/lng columns作成しました！
- package.json は開発の過程でイジって消してしまっていただけなので無視してください。mm

2021-04-07 10:57 UTC, Jumpo-523 commented on geodata/scraping_n_geocoding.ipynb
> +{
なるほど、確かに色々データ増やすことを考えると、DBサーバ/ストレージサービスに入れておくとかありですね。
やるかもリストに入れておきましょうか！
ちなみにベクトルタイルマップサーバーってどんなイメージでしょうか？

2021-04-07 14:40 UTC, aca-ta approved these changes
LGTMです！

2021-04-08 12:08 UTC, merged